FROM golang:1.21-alpine3.17 as builder

RUN apk add -U make

WORKDIR /usr/src/newrelic-k8s-metrics-adapter

COPY go.mod .

RUN go mod download

COPY . .

RUN make

FROM alpine:3.20

COPY --from=builder /usr/src/newrelic-k8s-metrics-adapter/newrelic-k8s-metrics-adapter /usr/local/bin/

ENTRYPOINT ["newrelic-k8s-metrics-adapter"]
