# Taken from https://github.com/tilt-dev/tilt-helm-demo/blob/d555fabbb1b3110582fb9d4f4e59c7d2ea337d37/values-dev.yaml.
image:
  repository: newrelic-k8s-metrics-adapter
  tag: latest
  pullPolicy: Never

restartPolicy: Never

config:
  externalMetrics:
    # This metric is used in e2e tests.
    # The sub-query is added to allow adding where conditions over the attribute.
    # The latest func is added to remove timestamp on the result since timestamp from const values have undefined behavior.
    e2e:
      query: "SELECT latest(attributeName) FROM (SELECT 0.123 AS 'attributeName' FROM NrUsage)"
      removeClusterFilter: true
