{{ if .Values.certManager.enabled }}
---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "newrelic-k8s-metrics-adapter.fullname.self-signed-issuer" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-root-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "newrelic.common.naming.fullname" . }}-root-cert
  duration: 43800h0m0s # 5y
  issuerRef:
    name: {{ include "newrelic-k8s-metrics-adapter.fullname.self-signed-issuer" . }}
  commonName: "ca.webhook.nri"
  isCA: true
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "newrelic-k8s-metrics-adapter.fullname.root-issuer" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ include "newrelic.common.naming.fullname" . }}-root-cert
---

# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "newrelic-k8s-metrics-adapter.fullname.webhook-cert" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "newrelic-k8s-metrics-adapter.name.apiservice" . }}
  duration: 8760h0m0s # 1y
  issuerRef:
    name: {{ include "newrelic-k8s-metrics-adapter.fullname.root-issuer" . }}
  dnsNames:
  - {{ include "newrelic.common.naming.fullname" . }}
  - {{ include "newrelic.common.naming.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "newrelic.common.naming.fullname" . }}.{{ .Release.Namespace }}.svc
{{ end }}