apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "newrelic-k8s-metrics-adapter.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yaml: |
    accountID: {{ .Values.config.accountID | required "config.accountID is required" }}
    {{- with (include "newrelic-k8s-metrics-adapter.region" .) }}
    region: {{ . }}
    {{- end }}
    cacheTTLSeconds: {{ .Values.config.cacheTTLSeconds | default "0" }}
    {{- with .Values.config.externalMetrics }}
    externalMetrics:
      {{- toYaml . | nindent 6 }}
    {{- end }}
