apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "common.naming.fullname" . }}:external-metrics
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch
