apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.naming.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
