global:
  cluster: test-cluster

personalAPIKey: "a21321"
verboseLog: false

config:
  accountID: 111
  region: EU

extraEnv:
  - name: ENV_VAR1
    value: "var1"
  - name: ENV_VAR2
    value: "var2"
extraVolumes:
  - name: tmpfs-data
    emptyDir: {}
extraVolumeMounts:
  - mountPath: /var/db/newrelic-infra/data
    name: tmpfs-data
hostNetwork: true
tolerations:
  - key: "key1"
    operator: "Exists"
    effect: "NoSchedule"
nodeSelector:
  kubernetes.io/os: linux
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux

apiServicePatchJob:
  volumes:
    - name: tmpfs-data
      emptyDir: {}
  volumeMounts:
    - mountPath: /var/db/newrelic-infra/data
      name: tmpfs-data

image:
  repository: e2e/newrelic-metrics-adapter
  tag: "test"  # Defaults to AppVersion
