apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- if .Values.certManager.enabled }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ printf "%s/%s-root-cert" .Release.Namespace (include "common.naming.fullname" .) | quote }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-root-cert" .Release.Namespace (include "common.naming.fullname" .) | quote }}
{{- end }}
spec:
  service:
    name: {{ template "common.naming.fullname" . }}
    namespace: {{ .Release.Namespace }}
  group: external.metrics.k8s.io
  version: v1beta1
  groupPriorityMinimum: 100
  versionPriority: 100
